"""Add whatsapp_number to Canteen

Revision ID: 8430c4a2a601
Revises: 
Create Date: 2026-04-14 15:48:12.581202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8430c4a2a601'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canteens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canteens', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_number')

    # ### end Alembic commands ###
